name: Beta release

on:
  push:
    branches:
      - beta

jobs:
  build:
    name: Build docker images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: beta

      - name: Declare the docker tags variable
        shell: bash
        run: |
          echo "SHORT_SHA=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
          echo "DATE_TAG=$(date -u +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Declare image tag
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            exbee/anjani
          tags: |
            type=raw,value=beta.latest
            type=raw,value=beta.${{ env.DATE_TAG }}
            type=raw,value=beta.${{ env.SHORT_SHA }}
      - name: build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          file: "./Dockerfile"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
    name: Update anjani images
    needs: build
    runs-on: p060
    steps:
      - name: Auto update on production environment
        run: |
          ssh -T beecon <<'EOL'
            pushd /home/ops/anjani
            pushd session
            mv anjani.latest.session anjani.latest.old
            sqlite3 anjani.latest.session.old '.clone anjani.latest.session'
            popd
            docker compose up -d --build --no-deps --pull always
            docker image prune --force
          EOL